//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=1.1.4322.2032.
// 
using System.ComponentModel;
using System.IO;
using System.Xml.Serialization;

namespace Fias.Update.Lib
{
    /// <remarks/>
    [XmlRoot("Fias.Update", Namespace = "", IsNullable = false)]
    public class FiasUpdate : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;
        private void NotifyPropertyChanged(string propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
        /// <remarks/>
        private string connectionString = string.Empty;
        public string ConnectionString { get { return connectionString; } set { connectionString = value; NotifyPropertyChanged("ConnectionString"); } }
        public void SaveToFile(string aFileName)
        {
            using (var stream = new FileStream(aFileName, FileMode.Create, FileAccess.Write))
            {
                var serializer = new XmlSerializer(typeof(FiasUpdate));
                serializer.Serialize(stream, this);
            }
        }
        public static FiasUpdate LoadFromFile(string aFileName)
        {
            using (var stream = new FileStream(aFileName, FileMode.Open, FileAccess.Read))
            {
                var serializer = new XmlSerializer(typeof(FiasUpdate));
                return (FiasUpdate)serializer.Deserialize(stream);
            }
        }
    }
}
